- switch:
    - name: Vacation Mode
      state: "{{ is_state('input_boolean.vacation_mode', 'on') }}"
      default_entity_id: switch.vacation_mode
      icon: mdi:palm-tree
      turn_on:
        - action: input_boolean.turn_on
          target:
            entity_id:
              - input_boolean.vacation_mode
      turn_off:
        - action: input_boolean.turn_off
          target:
            entity_id:
              - input_boolean.vacation_mode
